### ISSUE TITLE
Ability to select all components in "Select components" dialog

### ISSUE THREAD

**Issue by icnocop** [sebasbaumh/WixEdit#2]
Hi.

Thank you for WixEdit.

I'd like the ability to select all components in the "Select components" dialog.

For example, right-click on a Feature and select "Select Components to add".

In the "Select components" dialog, I expected to press Ctrl+A to select all components.

Thank you.

**Comment by icnocop** [comment]
Created separate repository here: https://github.com/WixEdit/WixEdit

**Comment by sebasbaumh** [comment]
Thank you @icnocop.
I am currently not actively working on that project, so it's good if you maintain a fork.
